title: "GIF-3004 : Laboratoire 1"
name: "Christian Gagné"
email: christian.gagne@gel.ulaval.ca

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
   - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      toc: true
      toc_label: "Table des matières"
      sidebar:
        - title: "Systèmes embarqués temps réel - GIF-3004"
          image: https://setr-ulaval.github.io/img/UL-logo.svg
          image_alt: "Université Laval"
          children:
            - title: "Site GIF-3004"
              url: https://setr-ulaval.github.io
            - title: "GEL-GIF"
              url: https://www.gelgif.ulaval.ca/
            - title: "Université Laval"
              url: https://www.ulaval.ca/
