theme: jekyll-theme-minimal
title: Systèmes embarqués temps réel - GIF-3004
description: "Professeur:" <A HREF="https://vision.gel.ulaval.ca/~cgagne">Christian Gagné</A>
logo: https://setr-ulaval.github.io/img/UL-logo.svg
show_downloads: false
